version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - my_network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - my_network

  cache:
    image: redis:6.2
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - my_network

  storage:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    networks:
      - my_network
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  my_network: