version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis://cache:6379
      - REDIS_PASSWORD="test"
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
      - AUTH0_DOMAIN=dev-12345.us.auth0.com
      - AUTH0_AUDIENCE=https://api.example.com
      - S3_ENDPOINT=http://storage:9000
      - AWS_ACCESS_KEY_ID=minio_access_key
      - AWS_SECRET_ACCESS_KEY=minio_secret_key
    depends_on:
      - db
      - cache
      - storage
    networks:
      - my_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my_network

  cache:
    image: redis:6.2
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD="test"
    networks:
      - my_network

  storage:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    volumes:
      - minio_data:/data
    networks:
      - my_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  my_network:
